# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TimelyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'DGActivityIndicatorView'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

  # Pods for TimelyDemo

end
